// Generated by https://quicktype.io

export interface Patient {
  id?:                number;
  idNumber?:          string;
  firstName?:         string;
  lastName?:          string;
  isMember?:          boolean;
  confirmed?:         boolean;
  city?:              string;
  province?: string;
  mobileNumber?:      string;
  emailAddress?:      string;
  memberNumber?:        string;
  employer?:          string;
  position?:          string;
  allergies?:         boolean;
  chronicMedication?: string;
  dateOfBirth?: string;
  appointmentDate?:   string;
  createdOn?:         string;
  createdby?:         string;
  updatedOn?:         string;
  updatedby?:        string;
  deleted?:           boolean;
  deletedOn?:         string;
  deletedBy?:         string;
  schemeName?: string;
}

interface Registration {
  id?: number;
  referenceNumber?: string;
  idNumber?: string;
  firstName?: string;
  lastName?: string;
  isMember?: boolean;
  confirmed?: boolean;
  city?: string;
  province?: string;
  siteId?: number;
  mobileNumber?: string;
  emailAddress?: string;
  memberNumber?: string;
  schemeName?: string;
  employer?: string;
  position?: string;
  allergies?: boolean;
  chronicMedication?: string;
  vaccinationInfo?: VaccinationInfo[];
  appointmentDate?: string;
  dateOfBirth?: string;
  createdOn?: string;
  createdby?: string;
  updatedOn?: string;
  updatedby?: string;
  deleted?: boolean;
  deletedOn?: string;
  deletedBy?: string;
}

export interface VaccinationInfo {
  id: number;
  memberId: number;
  vaccinationSiteId: number;
  vaccinatorid: number;
  feedBack: string;
  repeatInoculatedOn: string;
  inoculatedOn: string;
  dosageRecieved: string;
  doseNumber: number;
  vaccinatedDate: string;
  createdOn: string;
  createdby: string;
  updatedOn: string;
  updatedby: string;
  deleted: boolean;
  deletedOn: string;
  deletedBy: string;
}
